# Generated by Django 4.2.7 on 2023-12-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('quote', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
